<?php
?>

<?php
$arrayParams = $block->getRequest()->getParams();
?>
<?php if (isset($arrayParams["affiliate"]) && $arrayParams['affiliate'] == "true") {
    echo `<div id="product-review-container" data-role="product-review"></div>`;
    echo $block->getChildHtml();
} ?>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Review/js/process-reviews": {
                "productReviewUrl": "<?= $block->escapeJs($block->getProductReviewUrl()) ?>",
                "reviewsTabSelector": "#tab-label-reviews"
            }
        }
    }
</script>