<?php
$collection = $block->getEmployeeCollection();
?>
<table>
    <thead>
        <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($collection as $employee): ?>
            <tr>
                <td><?= $employee->getData('first_name') ?></td>
                <td><?= $employee->getData('last_name') ?></td>
                <td><?= $employee->getData('email_id') ?></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>