<form action="<?= $block->getUrl('Userstory8a/Index/Save') ?>" method="post">
    <input type="text" name="first_name" placeholder="First Name" required>
    <input type="text" name="last_name" placeholder="Last Name" required>
    <input type="email" name="email_id" placeholder="Email" required>
    <input type="text" name="address" placeholder="Address" required>
    <input type="text" name="phone_number" placeholder="Phone Number" required>
    <input type="submit" value="Submit Data">
</form>